# Generated by Django 4.0.4 on 2022-05-11 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_at', models.DateTimeField(auto_now=True)),
                ('parameters_link', models.CharField(blank=True, max_length=120, null=True)),
                ('aggregation', models.TextField(blank=True, null=True)),
                ('location_id', models.CharField(max_length=120)),
                ('location_name', models.CharField(max_length=120)),
                ('location_avail_params', models.TextField(blank=True, null=True)),
                ('location_lat', models.CharField(default='0', max_length=120)),
                ('location_lon', models.CharField(default='0', max_length=120)),
                ('location_timezone', models.CharField(default='0', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apiname', models.CharField(max_length=120, unique=True)),
                ('urllink', models.CharField(max_length=120, unique=True)),
                ('querystring', models.TextField()),
                ('headers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastupdate_at', models.DateTimeField(auto_now=True)),
                ('latest_value', models.TextField(blank=True, null=True)),
                ('values', models.TextField(blank=True, null=True)),
                ('aggregation', models.TextField(blank=True, null=True)),
                ('unitsofmeasurment', models.CharField(max_length=120, null=True)),
                ('parameter_key_name', models.CharField(max_length=120)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
        ),
    ]
