# Generated by Django 4.0.4 on 2022-05-17 10:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('location', '0004_alter_parameter_unitsofmeasurment'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('location_name', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='parameter',
            unique_together={('location', 'parameter_key_name')},
        ),
    ]
